[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

# Temporarily disable the plugin
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/pages/*"
  to = "/404"
  status = 404
